# Generated by Django 3.0.3 on 2020-06-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Designation', models.CharField(blank=True, max_length=50, null=True)),
                ('Organization', models.CharField(blank=True, max_length=100, null=True)),
                ('Office_Address', models.TextField(blank=True, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Telephone_Office', models.TextField(blank=True, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('Other_Professional_Updates', models.BooleanField(blank=True, null=True)),
                ('Query_Content', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
