# Generated by Django 3.0.3 on 2020-06-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100, null=True)),
                ('Last_Name', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('Postion', models.CharField(blank=True, max_length=50, null=True)),
                ('DOB', models.DateTimeField()),
                ('Qualification', models.CharField(max_length=200, null=True)),
                ('Portfolio_Website', models.CharField(max_length=50, null=True)),
                ('RCQ', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
