# Generated by Django 3.0.3 on 2020-06-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='Subject_of_Query',
            field=models.CharField(choices=[('Income_Tax', 'Income Tax'), ('Audit', 'Audit'), ('Service_Tax', 'Service Tax'), ('Company_Law', 'Company Law'), ('Excise_Duty', 'Excise Duty'), ('Customs', 'Customs'), ('Wealth_Tax', 'Wealth Tax'), ('ST/VAT', 'Sales Tax / Value Added Tax'), ('FEMA', 'FEMA'), ('RBI', 'RBI'), ('Labour_Law', 'Labour_Law'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
