# Generated by Django 3.0.3 on 2020-06-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_auto_20200622_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='DOB',
            field=models.DateField(),
        ),
    ]
