# Generated by Django 3.0.3 on 2020-06-22 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_auto_20200622_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='Other_Professional_Updates',
        ),
    ]
