# Generated by Django 3.0.8 on 2020-07-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_remove_query_other_professional_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
