# Generated by Django 3.0.8 on 2020-07-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_auto_20200707_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
