# Generated by Django 3.0.8 on 2020-08-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_auto_20200807_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='Experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='Portfolio_Website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='Qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
