# Generated by Django 3.0.8 on 2020-08-09 15:02

import baseapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_auto_20200809_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[baseapp.validators.validate_file_extension]),
        ),
    ]
